---
- name: 'Provision image'
  hosts: default
  become: true
  tasks:
    - name: Update the apt-get
      apt:
        update_cache: yes
    - name: Install nginx
      apt:
        name: nginx
        state: latest