---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    permissions:
        packages: write
        contents: read
        id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: AWS Authentication # we talked to aws 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::699330879220:role/github-actions-oidc
          aws-region: ap-south-1
          role-session-name: GithubAMI-PACKERDeploy

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: aws-ubuntu-nginx.pkr.hcl
          working_directory: packer/

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: aws-ubuntu-nginx.pkr.hcl
          working_directory: packer/